name: atmos terraform plan
run-name: atmos terraform plan ${{ github.event.inputs.atmos_pro_run_id}}
on:
  workflow_dispatch:
    inputs:
      component:
        type: string
      stack:
        type: string
      atmos_pro_run_id:
        type: string
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: plan
        shell: bash
        run: echo "atmos terraform plan ${{ github.event.inputs.component }} -s ${{ github.event.inputs.stack }}"
