name: Atmos Affected Stacks
on:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]
jobs:
  affected:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dump context
        shell: bash
        run: |
          echo '${{ toJSON(github) }}'
      - name: Set COMMIT_SHA for pull request or release
        id: set-sha
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: affected
        shell: bash
        run: |
          set -x -e
          cat affected.template.json|envsubst > affected.json
          cat affected.json
          curl -X POST -H "Content-Type: application/json" -d @affected.json https://ngrok.mattcalhoun.com/api/affected-stacks
