name: Atmos Affected Stacks
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  affected:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: affected
        shell: bash
        env:
          PR_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          set -x -e
          cat affected.template.json|envsubst > affected.json
          cat affected.json
          curl -X POST -H "Content-Type: application/json" -d @affected.json https://ngrok.mattcalhoun.com/api/affected-stacks
