name: Dynamic Workflow Dispatcher

on:
  workflow_dispatch:

jobs:
  generate-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Workflow File
        run: |
          echo "name: Dynamic Generated Workflow" > ./github/workflows/generated_workflow.yml
          echo "on:" >> ./github/workflows/generated_workflow.yml
          echo "  push:" >> ./github/workflows/generated_workflow.yml
          echo "    branches:" >> ./github/workflows/generated_workflow.yml
          echo "      - main" >> ./github/workflows/generated_workflow.yml
          echo "jobs:" >> ./github/workflows/generated_workflow.yml
          echo "  build:" >> ./github/workflows/generated_workflow.yml
          echo "    runs-on: ubuntu-latest" >> ./github/workflows/generated_workflow.yml
          echo "    steps:" >> ./github/workflows/generated_workflow.yml
          echo "      - name: Checkout" >> ./github/workflows/generated_workflow.yml
          echo "        uses: actions/checkout@v4" >> ./github/workflows/generated_workflow.yml
          echo "       - run: echo Hello, World!" >> ./github/workflows/generated_workflow.yml

      - name: Dispatch Generated Workflow
        uses: ./github/workflows/generated_workflow.yml
