name: Dynamic Workflow Dispatcher
on:
  workflow_dispatch:
jobs:
  run-plan-and-apply:
    name: ${{matrix.root}}/${{matrix.component}}/${{matrix.stack}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - root: component1
            component: component1
            stack: dev
          - root: component1
            component: component2
            stack: dev
          - root: component1
            component: component3
            stack: dev
          - root: component4
            component: component4
            stack: dev
          - root: component4
            component: component5
            stack: dev
          - root: component4
            component: component6
            stack: dev
    concurrency:
      group: ${{matrix.root}}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - run: echo "atmos terraform plan ${{matrix.component}} -s ${{matrix.stack}}"
        shell: bash
      - run: echo "atmos terraform apply ${{matrix.component}} -s ${{matrix.stack}}"
        shell: bash
