name: Dynamic Workflow Dispatcher

on:
  workflow_dispatch:

jobs:
  generate-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Workflow File
        run: |
          echo "name: Dynamic Generated Workflow" >   /./github/workflows/generated_workflow.yml
          echo "on:" >> ${GITHUB_WORKSPACE}/./github/workflows/generated_workflow.yml
          echo "  push:" >> ${GITHUB_WORKSPACE}/./github/workflows/generated_workflow.yml
          echo "    branches:" >> ${GITHUB_WORKSPACE}/./github/workflows/generated_workflow.yml
          echo "      - main" >> ${GITHUB_WORKSPACE}/./github/workflows/generated_workflow.yml
          echo "jobs:" >> ${GITHUB_WORKSPACE}/./github/workflows/generated_workflow.yml
          echo "  build:" >> ${GITHUB_WORKSPACE}/./github/workflows/generated_workflow.yml
          echo "    runs-on: ubuntu-latest" >> ${GITHUB_WORKSPACE}/./github/workflows/generated_workflow.yml
          echo "    steps:" >> ${GITHUB_WORKSPACE}/./github/workflows/generated_workflow.yml
          echo "      - name: Checkout" >> ${GITHUB_WORKSPACE}/./github/workflows/generated_workflow.yml
          echo "        uses: actions/checkout@v4" >> ${GITHUB_WORKSPACE}/./github/workflows/generated_workflow.yml
          echo "       - run: echo Hello, World!" >> ${GITHUB_WORKSPACE}/./github/workflows/generated_workflow.yml

      - name: Dispatch Generated Workflow
        uses: ./github/workflows/generated_workflow.yml
