name: Dynamic Workflow Dispatcher
on:
  workflow_dispatch:
jobs:
  generate-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cloudposse/github-action-atmos-dependencies-test@feature/initial-implementation
        with:
          levels: 2
      - uses: actions/upload-artifact@v4
        with:
          name: generated-dynamic-dependencies
          path: ./.generated-dynamic-dependencies

  run-workflow:
    runs-on: ubuntu-latest
    needs: generate-workflow
    strategy:
      matrix:
        include:
          - root: "component1"
            name: "step1"
          - root: "component1"
            name: "step2"
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.root-component }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: generated-dynamic-dependencies
          path: ./.generated-dynamic-dependencies
      - uses: ./.generated-dynamic-dependencies/${{ matrix.root }}/${{ matrix.name }}
